app:
  env: pro
  port: 8888
  app_name: Mercury
  app_url: http://localhost

log:
  level: info
  root_dir: ./logs
  file_name: app.log
  format: json
  show_line: true
  max_backups: 10
  max_size: 200
  max_age: 7
  compress: true

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  database: mercury
  username: root
  password: ""
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: info
  enable_file_log_writer: true
  log_filename: sql.log